### ISSUE TITLE
上传失败

### ISSUE THREAD

**Issue by TwinIsland** [dishcheng/cosUploadV5#5]
id和key能确定是填对了的，但还是无法上传成功，烦请大佬指教
![Snipaste_2021-12-23_01-41-38](https://user-images.githubusercontent.com/66999583/147206401-7458662f-4fc4-458f-abe3-5c40bcfe43fe.png)

**Comment by TwinIsland** [comment]
刚才又试了试，发现只有图片存在这个问题，上传后会一直加载，控制台里也会报错，但是刷新页面后图片又会显示以上传成功，玄学

**Comment by TwinIsland** [comment]
没问题了，不是这个插件的原因，之前下的另一个插件调用getimgsize的时候没考虑远程图片资源的适配性，导致上传图片一直加载。把地址写死就ok了

**Comment by inkss** [comment]
什么意思？怎么解决的呀
